-- Bootstrap all domain schemas, sequences, and set search_path.
-- This migration runs FIRST (in the user / pos_identity module) so that every
-- subsequent module's Flyway can create tables inside the correct schema.
CREATE SCHEMA IF NOT EXISTS "pos_identity";
CREATE SCHEMA IF NOT EXISTS "pos_merchant";
CREATE SCHEMA IF NOT EXISTS "pos_catalog";
CREATE SCHEMA IF NOT EXISTS "pos_order";
CREATE SCHEMA IF NOT EXISTS "pos_transaction";

-- ── Hibernate reactive calls nextval('schema.table_seq') ───────────────────
-- We create all sequences here with the _seq suffix that Hibernate expects.
-- Each migration then uses: DEFAULT nextval('schema.table_seq') for the ID column.
-- This avoids the conflict between PG's GENERATED BY DEFAULT AS IDENTITY
-- (which creates table_column_id_seq) and Hibernate's IDENTITY strategy
-- (which calls table_seq).

-- pos_identity tables
CREATE SEQUENCE IF NOT EXISTS "pos_identity"."users_seq";
CREATE SEQUENCE IF NOT EXISTS "pos_identity"."roles_seq";
CREATE SEQUENCE IF NOT EXISTS "pos_identity"."user_roles_seq";
CREATE SEQUENCE IF NOT EXISTS "pos_identity"."refresh_tokens_seq";
CREATE SEQUENCE IF NOT EXISTS "pos_identity"."reset_tokens_seq";

-- pos_merchant tables
CREATE SEQUENCE IF NOT EXISTS "pos_merchant"."merchants_seq";
CREATE SEQUENCE IF NOT EXISTS "pos_merchant"."cashiers_seq";
CREATE SEQUENCE IF NOT EXISTS "pos_merchant"."merchant_documents_seq";

-- pos_catalog tables
CREATE SEQUENCE IF NOT EXISTS "pos_catalog"."categories_seq";
CREATE SEQUENCE IF NOT EXISTS "pos_catalog"."products_seq";

-- pos_order tables
CREATE SEQUENCE IF NOT EXISTS "pos_order"."orders_seq";
CREATE SEQUENCE IF NOT EXISTS "pos_order"."order_items_seq";
CREATE SEQUENCE IF NOT EXISTS "pos_order"."outbox_seq";

-- pos_transaction tables
CREATE SEQUENCE IF NOT EXISTS "pos_transaction"."transactions_seq";

-- Set the default search_path for the application role so that unqualified
-- table references (including Hibernate native queries) resolve correctly.
-- IMPORTANT: This is idempotent — re-running on an existing role is safe.
ALTER ROLE CURRENT_USER SET search_path = pos_identity, pos_merchant, pos_catalog, pos_order, pos_transaction, public;
