CREATE TABLE IF NOT EXISTS "pos_identity"."users" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "firstname" VARCHAR(100) NOT NULL,
    "lastname" VARCHAR(100) NOT NULL,
    "username" VARCHAR(100) UNIQUE NOT NULL,
    "email" VARCHAR(100) UNIQUE NOT NULL,
    "password" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMP DEFAULT NULL
);


CREATE INDEX IF NOT EXISTS idx_users_email ON "pos_identity"."users" ("email");
CREATE INDEX IF NOT EXISTS idx_users_firstname ON "pos_identity"."users" ("firstname");
CREATE INDEX IF NOT EXISTS idx_users_lastname ON "pos_identity"."users" ("lastname");
CREATE INDEX IF NOT EXISTS idx_users_username ON "pos_identity"."users" ("username");
CREATE INDEX IF NOT EXISTS idx_users_created_at ON "pos_identity"."users" ("created_at");
