-- merchant_documents table (document_id is the PK, matching entity @Id)
CREATE TABLE IF NOT EXISTS "pos_merchant"."merchant_documents" (
    "document_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "merchant_id" INT NOT NULL,
    "document_type" VARCHAR(255) NOT NULL,
    "document_url" VARCHAR(255) NOT NULL,
    "status" VARCHAR(255) NOT NULL DEFAULT 'PENDING',
    "note" VARCHAR(255),
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMP DEFAULT NULL
);

CREATE INDEX IF NOT EXISTS idx_merchant_documents_merchant_id ON "pos_merchant"."merchant_documents" ("merchant_id");
